apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-ecr-eks-demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: 256707027015.dkr.ecr.ca-central-1.amazonaws.com/skith/docker-ecr-eks:1fc746d3b95151980048840074163f68035694f3
          imagePullPolicy: Always
          ports:
          - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-ecr-eks-demo-app-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: docker-ecr-eks-demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000