apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-ecr-eks-demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: 256707027015.dkr.ecr.ca-central-1.amazonaws.com/skith/docker-ecr-eks:a17b6e1c7675152fa2488b0d7bc5b499ca1d409c
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: docker-ecr-eks-demo-app-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: docker-ecr-eks-demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080